### ISSUE TITLE
Install Heap by Sun 4/11 on technovationchallenge.org Wordpress

### ISSUE THREAD

**Issue by rsgonzal** [Iridescent-CM/technovation-wp#95]
Follow on from [#2754](https://github.com/Iridescent-CM/technovation-app/issues/2754), which installed Heap to the TG platform.

Deliverable: Install the Heap code snippet on the technovationchallenge.org wordpress site. Our goal is to see user behavior across BOTH the TG platform (my.technovationchallenge.org) and the website (technovationchallenge.org). 

Importantly, our curriculum/lessons are on the wordpress site, so Heap going there will allow us to see how students interact with our materials, and what if any effect that has on submissions. 

Developer instructions are at https://developers.heap.io/docs/wordpress

**Comment by congdang-agilityio** [comment]
@rsgonzal Can you provide us the Heap account for staging? So we can login to to get the APP ID and also after applied, we can check it data has been sent to Heap or not.

Thanks,

**Comment by ghost** [comment]
@rsgonzal I have embedded Heap code snippet on header for the technovationchallenge.org wordpress site. Please help to verify. Thanks!

**Comment by rsgonzal** [comment]
Hi @thaopham-agilityio we're not seeing the code. It might be that when our team pushed live, they may have overwritten it. Is it possible for you to install on staging and we can try that?

**Comment by ghost** [comment]
@rsgonzal I've installed the Heap code snippet on the staging wordpress site (http://technovation.staging.wpengine.com/). Please double check.

Thanks,

**Comment by ghost** [comment]
I can confirm that the code appeared on staging, and when pushed live just now also appeared on production. Looks good!

**Comment by ghost** [comment]
@mjaris Thanks for the confirmation.
