### ISSUE TITLE
Technovation.org — App Gallery Expanded Categories + Search Functionality 

### ISSUE THREAD

**Issue by ghost** [Iridescent-CM/technovation-wp#97]
**Website:** Technovation.org, specifically the app gallery (https://www.technovation.org/app-gallery/) 

**Problem:** We would like to expand the search functionality of the app gallery to include the text inside "app placement" labels
Ex: If I wanted to see all apps related to social justice, I could search for "social justice"; or if I wanted to search for "1st place winners" entering that text in the search menu would return results.

Currently, searching for those terms does not return results, although there are several apps tagged "social justice" or "1st place"
<img width="1072" alt="Screen Shot 2021-04-13 at 7 05 52 PM" src="https://user-images.githubusercontent.com/10146704/114631826-5677a180-9c8b-11eb-8a6e-b92a9acf9540.png">
<img width="1092" alt="Screen Shot 2021-04-13 at 7 05 28 PM" src="https://user-images.githubusercontent.com/10146704/114631831-58416500-9c8b-11eb-8fb4-c50d213b0d2b.png">

**See the problem:** you can see the issue by navigating to the home page of the app gallery (https://www.technovation.org/app-gallery/) and trying to use the search bar to find "Social justice" "civic engagement" "1st place" or any of the text in the labels at the top of an app entry (they're colorful "flags") 

**Notes**:  The App Gallery is a custom module built for us. The categories of "1st place" or "social justice" are referred to as "app placements" in this module. 

I think we're open to either improved search bar functionality or adding in an additional drop down menu to filter the items.

**Comment by tamtran-agilityio** [comment]
@rsgonzal @mjaris  We have improved search on staging https://techstage19.wpengine.com/app-gallery. Pls help me check, thanks!

**Comment by jarism** [comment]
Confirming that the search function is improved!

**Comment by tamtran-agilityio** [comment]
@jarism @rsgonzal We have deployment on production, thanks!
